class DimProduct:
    """dim_product 的显式列名映射。"""

    __tablename__ = "dim_product"
    columns = {
        "seq_no": "seq_no",
        "product_code": "sku_id",
        "international_barcode": "international_barcode",
        "product_name": "product_name",
        "product_created_at": "product_created_at",
        "product_status": "product_status",
        "purchase_factor": "purchase_factor",
        "category_code": "category_code",
        "product_category": "sku_category",
        "brand_code": "brand_code",
        "product_brand": "product_brand",
        "purchase_price": "purchase_price",
        "unit": "unit",
        "specification": "specification",
        "distribution_price": "distribution_price",
        "shelf_life_days": "shelf_life_days",
        "origin": "origin",
        "supplier_code": "supplier_code",
        "supplier_name": "supplier_name",
        "wholesale_price": "wholesale_price",
        "retail_price": "retail_price",
        "member_price": "member_price",
        "member_price_1": "member_price_1",
        "member_price_2": "member_price_2",
        "input_tax_rate": "input_tax_rate",
        "output_tax_rate": "output_tax_rate",
        "gross_profit_rate": "gross_margin_rate",
        "daily_cost": "daily_cost",
        "inventory_qty": "inventory_qty",
        "inventory_amount": "inventory_amount",
        "daily_avg_sales": "avg_daily_sales",
        "pricing_method": "pricing_method",
        "business_method": "business_method",
        "hot_product_flag": "is_hot",
        "fresh_flag": "is_fresh",
        "points_flag": "points_flag",
        "picking_group": "picking_group",
        "creator": "creator",
        "remark_1": "remark_1",
        "remark_2": "remark_2",
        "remark_3": "remark_3",
    }
